/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Main/car.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const  Car = (props) => {
  const { nodes, materials } = useGLTF('models/Main/car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lamborghini_Aventador_Body.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
      <mesh geometry={nodes.Lamborghini_Aventador_Glass.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_GlassSG} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FL.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_RL.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_RR.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
    </group>
  )
}

useGLTF.preload('models/Main/car.glb')
