/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Map/department.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Department = (props)  => {
  const { nodes, materials } = useGLTF('models/Map/department.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cinema_mesh.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.ช้อความ.geometry} material={nodes.ช้อความ.material} position={[-2, 5.3, 2.6]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Map/department.glb')
