/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Map/Park.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Park (props) {
  const { nodes, materials } = useGLTF('models/Map/Park.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003_Cube010.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube002_Cube009.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube001_Cube008.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube000_Cube007.geometry} material={materials.None} />
      <mesh geometry={nodes.Cone_Cone026.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone001_Cone027.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone002_Cone028.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone003_Cone029.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone004_Cone030.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone005_Cone031.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cone006_Cone032.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Cube024_Cube041.geometry} material={materials.None} />
      <mesh geometry={nodes.Cube032_Cube028.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube033_Cube030.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube034_Cube031.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube035_Cube036.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube036_Cube037.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube037_Cube038.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube038_Cube039.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube039_Cube040.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube040_Cube044.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube041_Cube045.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube042_Cube046.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube043_Cube047.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube801_Cube3484.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cube802_Cube3485.geometry} material={materials.Road} />
      <mesh geometry={nodes.Cube803_Cube3486.geometry} material={materials['Gray.004']} />
      <mesh geometry={nodes.Cylinder061_Cylinder047.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder062_Cylinder063.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder063_Cylinder064.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder064_Cylinder065.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder065_Cylinder066.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder066_Cylinder067.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder067_Cylinder068.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder068_Cylinder069.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Cylinder069_Cylinder070.geometry} material={materials.Tree} />
      <mesh geometry={nodes.Icosphere162_Icosphere192.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Icosphere163_Icosphere193.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Icosphere164_Icosphere194.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Icosphere165_Icosphere195.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Plane_Plane008.geometry} material={materials.Street} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh'].geometry} material={materials['Orange.002']} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_1'].geometry} material={materials.BlackWindow} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_2'].geometry} material={materials['Orange.001']} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_3'].geometry} material={materials['Bar.001']} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_4'].geometry} material={materials['Wheel.001']} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_5'].geometry} material={materials.Wheels} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_6'].geometry} material={materials.Gas} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_7'].geometry} material={materials.Rings} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_8'].geometry} material={materials.Dial} />
      <mesh geometry={nodes['CarColored000_Cube3470-Mesh_9'].geometry} material={materials.REd} />
      <mesh geometry={nodes['Cube030_Cube042-Mesh'].geometry} material={materials.Grass} />
      <mesh geometry={nodes['Cube030_Cube042-Mesh_1'].geometry} material={materials.Sidewalk} />
      <mesh geometry={nodes['Cube905_Cube3610-Mesh'].geometry} material={materials.Sidewalk} />
      <mesh geometry={nodes['Cube905_Cube3610-Mesh_1'].geometry} material={materials.Grass} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_1'].geometry} material={materials.Blue} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_2'].geometry} material={materials.Chairwheel} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_3'].geometry} material={materials.AA} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_4'].geometry} material={materials['Bar.000']} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_5'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_6'].geometry} material={materials.Window} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_7'].geometry} material={materials.darker} />
      <mesh geometry={nodes['Cube916_Cube3629-Mesh_8'].geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('models/Map/Park.glb')
