/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Prop/prop3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Prop3 (props) {
  const { nodes, materials } = useGLTF('models/Prop/prop3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cop_Cube001-Mesh'].geometry} material={materials.White} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_1'].geometry} material={materials.Windows} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_2'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_3'].geometry} material={materials.Headlights} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_4'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_5'].geometry} material={materials.TailLights} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_6'].geometry} material={materials.WhiteLights} />
      <mesh geometry={nodes['Cop_Cube001-Mesh_7'].geometry} material={materials.BlueLights} />
      <mesh geometry={nodes['Cop_BackWheels_Cylinder001-Mesh'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Cop_BackWheels_Cylinder001-Mesh_1'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Cop_FrontLeftWheel_Cylinder011-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Cop_FrontLeftWheel_Cylinder011-Mesh_1'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Cop_FrontRightWheel_Cylinder012-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['Cop_FrontRightWheel_Cylinder012-Mesh_1'].geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('models/Prop/prop3.glb')
